### PR TITLE
Removed InsightUpdateQueue in Favor of ErrorAnnotator

### LINKED ISSUE #194: Support new refmt errors
plugin version: 
v0.82
### Description

Next [bs release](https://github.com/BuckleScript/bucklescript/pull/3945) will have better errors, unfortunately they are not detected by plugin. Install `bs-platform@^7.0.0-dev.1` for tests

Example of error:
```reason
let x = {
    foo;
```
error message looks like:
```reason
File "/File.re", line 14, characters 0-0:
Error: Unclosed "{" (opened line 12, column 8)
```

### PR DESCRIPTION
**Pull request by JohnPucciarelli**
Seems the InsightUpdateQueue was unnecessary and causing race conditions with error handling.

Peek 2020-12-01 12-30

Closes #194

### CODE REVIEW

File: idea-plugin/src/com/reason/CompilerORProcessException.java [hunk 1]
```diff
@@ -0,0 +1,19 @@
+package com.reason;
+
+import org.jetbrains.annotations.NotNull;
+
+public class CompilerORProcessException extends ORProcessException {
```
Comment (giraud) [inline idea-plugin/src/com/reason/CompilerORProcessException.java:5]: This is not used

File: idea-plugin/src/com/reason/bs/BsLineProcessor.java [hunk 2]
```diff
@@ -153,12 +156,15 @@ private OutputInfo extractExtendedFilePositions(@Nullable String text) {
   }
 
   // ...path/src/Source.re 111:21-112:22
+  // ...path/src/Source.re:111:21-112:22
   // ...path/src/Source.re 111:21-22
+  // ...path/src/Source.re:111:21-22
   // ...path/src/Source.re 111:21   <- must add 1 to colEnd
+  // ...path/src/Source.re:111:21   <- must add 1 to colEnd
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BsLineProcessor.java:163]: comments are duplicated

File: idea-plugin/src/com/reason/bs/BscProcess.java [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+    m_project = project;
+  }
+
+  @Nullable
+  public Integer run(
+      VirtualFile sourceFile, List<String> arguments, ProcessListener processListener)
+      throws ORProcessException {
+    Optional<VirtualFile> bscPath = BsPlatform.findBscExecutable(m_project, sourceFile);
+    if (!bscPath.isPresent()) {
+      throw new ORProcessException("Unable to find bsc.exe.");
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BscProcess.java:37]: I prefer to avoid exception here, and use warn log.
exceptions are very intrusive in the UI, and here we have a situation we can handle.

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 4]
```diff
@@ -1,113 +1,229 @@
...
+    Ninja ninja = bucklescript.readNinjaBuild(contentRoot.get());
+    for (String devSource : config.getDevSources()) {
+      VirtualFile devFile = contentRoot.get().findFileByRelativePath(devSource);
+      if (devFile != null && FileUtil.isAncestor(devFile.getPath(), sourceFile.getPath(), true)) {
+        ninja.addInclude(devSource);
       }
     }
 
-    return result;
+    if (!BsPlatform.findBscExecutable(project, sourceFile).isPresent()) {
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:100]: I have the feeling we are doing a lot of this. maybe just keep the test in BscProcess and remove the others ?

File: idea-plugin/src/com/reason/bs/BscProcess.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+    return ServiceManager.getService(project, BscProcess.class);
+  }
+
+  public BscProcess(Project project) {
+    m_project = project;
+  }
+
+  @Nullable
+  public Integer run(
+      VirtualFile sourceFile, List<String> arguments, ProcessListener processListener)
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BscProcess.java:33]: add @NotNull/@Nullable annotations

File: idea-plugin/src/com/reason/bs/BscProcess.java [hunk 6]
```diff
@@ -0,0 +1,62 @@
...
+    GeneralCommandLine bscCli =
+        new GeneralCommandLine(command)
+            .withWorkDirectory(sourceFile.getParent().getPath())
+            // disable coloring
+            // https://rescript-lang.org/docs/manual/latest/build-configuration#error-output-coloring-ninja_ansi_forced
+            .withEnvironment("NINJA_ANSI_FORCED", "0");
+
+    OSProcessHandler bscProcessHandler;
+    try {
+      bscProcessHandler = new ColoredProcessHandler(bscCli);
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BscProcess.java:52]: Is it needed to have Colored process handler, or just KillableProcessHandler is enough ?

File: idea-plugin/src/com/reason/bs/BscProcess.java [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+    } catch (ExecutionException e) {
+      throw new ORProcessException(e.getMessage());
+    }
+
+    bscProcessHandler.addProcessListener(processListener);
+    bscProcessHandler.startNotify();
+    bscProcessHandler.waitFor();
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BscProcess.java:59]: I'm always worried about using infinite wait, can we use waitFor with a reasonable timeout ?

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 8]
```diff
@@ -1,113 +1,229 @@
...
+    Project project = sourcePsiFile.getProject();
+    VirtualFile sourceFile = sourcePsiFile.getVirtualFile();
+
+    long compilationStartTime = System.currentTimeMillis();
+
+    BscProcess bscProcess = BscProcess.getInstance(project);
+    BscProcessListener bscListener = new BscProcessListener();
+
+    Integer exitCode = bscProcess.run(sourceFile, initialInfo.arguments, bscListener);
+    if (exitCode == null) {
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:166]: I would use `exitCode == null || exitCode != 0` here

File: idea-plugin/src/com/reason/bs/BscProcessListener.java [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+    public void onTextAvailable(@NotNull ProcessEvent event, @NotNull Key outputType) {
+        String text = event.getText();
+        if (text != null) {
+            m_builder.append(text);
+            if (text.endsWith("\n")) {
+                m_lineProcessor.onRawTextAvailable(m_builder.toString());
+                if (LOG.isTraceEnabled()) {
+                    LOG.trace(m_builder.toString().replace("\n", ""));
+                }
+                m_builder.setLength(0);
```
Comment (giraud) [inline idea-plugin/src/com/reason/bs/BscProcessListener.java:40]: I don't understand why you are using a StringBuilder instead of using text variable directly

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 10]
```diff
@@ -119,17 +235,121 @@ public void apply(
...
+    ReadAction.run(() -> annotateTypes(project, sourceFile, cmtFile));
+
+    problemSolver.reportProblems(sourceFile, problems);
+  }
+
+  @NotNull
+  public File createTempCompilationDirectory(Project project) {
+    String directoryName = "BS_" + project.getName().replaceAll(" ", "_");
+    try {
+      FileUtil.delete(Paths.get(FileUtil.getTempDirectory(), directoryName));
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:248]: do we need to delete it ? if it's already present, it's ok

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 11]
```diff
@@ -1,113 +1,229 @@
...
+    }
+
+    Optional<VirtualFile> contentRoot = BsPlatform.findContentRootForFile(project, sourceFile);
+    if (!contentRoot.isPresent()) {
+      LOG.info("Unable to find BuckleScript content root.");
+      return null;
+    }
+
+    VirtualFile bsExecutableDirectory = contentRoot.get().findFileByRelativePath("lib/bs");
+    if (bsExecutableDirectory == null) {
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:71]: why do you test this ? it seems useless to me

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 12]
```diff
@@ -1,113 +1,229 @@
...
+      LOG.info("Unable to find lib/bs for BuckleScript project.");
+      return null;
+    }
+
+    // Read bsConfig to get the jsx value and ppx
+    // @TODO register a file listener for bsconfig.json
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:77]: I don't understand the TODO

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 13]
```diff
@@ -1,113 +1,229 @@
...
+    VirtualFile bsConfigFile = contentRoot.get().findFileByRelativePath("bsconfig.json");
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:78]: you could use com.reason.ide.files.BsConfigJsonFileType#FILENAME

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 11 above)
Comment (giraud) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:71]: in fact, it will be covered by readNinjaBuild later

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 14]
```diff
@@ -1,113 +1,229 @@
...
 
-    return result;
+    if (!BsPlatform.findBscExecutable(project, sourceFile).isPresent()) {
+      LOG.info("Unable to find bsc.exe");
+      return null;
+    }
+
+    // Creates a temporary file on disk with a copy of the current document.
+    // It'll be used by bsc for a temporary compilation
+    Path tempFilePath = Paths.get(m_compilationDirectory.getPath(), sourceFile.getName());
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:107]: This file MUST be deleted at the end of the process

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 15]
```diff
@@ -1,113 +1,229 @@
...
+    try {
+      Files.write(tempFilePath, psiFile.getText().getBytes());
+    } catch (IOException e) {
+      LOG.error("Failed to write to temporary file.", e);
+      return null;
+    }
+    LOG.debug("Wrote contents to temporary file.", tempFilePath);
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:114]: LOG.trace ?

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 16]
```diff
@@ -1,113 +1,229 @@
...
-  public Collection<BsbErrorAnnotation> doAnnotate(
-      @NotNull Collection<BsbErrorAnnotation> collectedInfo) {
-    return collectedInfo.isEmpty() ? null : collectedInfo;
+  public AnnotationResult doAnnotate(@Nullable InitialInfo initialInfo) {
+    if (initialInfo == null) {
+      LOG.warn("Unable to annotate file. Annotator not ready.");
+      return null;
+    }
+
+    PsiFile sourcePsiFile = Objects.requireNonNull(initialInfo.sourcePsiFile);
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:156]: requireNonNull shouldn't be required

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 17]
```diff
@@ -1,113 +1,229 @@
...
+
+    if (exitCode == 0) {
+      ApplicationManager.getApplication()
+          .invokeLater(
+              () -> {
+                if (!project.isDisposed()) {
+                  PsiFile psiFile = PsiManager.getInstance(project).findFile(sourceFile);
+                  if (psiFile != null) {
+                    LOG.trace("Restart daemon code analyzer for " + psiFile);
+                    DaemonCodeAnalyzer.getInstance(project).restart(psiFile);
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:180]: Is that really needed ? I used that code to force a restart of the external annotator. 
But here we are already running that annotator

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 18]
```diff
@@ -1,113 +1,229 @@
...
+              });
+      return null;
+    }
+
+    List<OutputInfo> outputInfo = bscListener.getInfo();
+    LOG.debug("Found info", outputInfo);
+    String name = sourceFile.getName();
+    for (OutputInfo info : outputInfo) {
+      info.path = name;
+      LOG.trace("  -> " + info);
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:192]: protect with LOG.isTraceEnabled

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java [hunk 19]
```diff
@@ -119,17 +235,121 @@ public void apply(
...
+    LogicalPosition start =
+        new LogicalPosition(lineStart < 1 ? 0 : lineStart - 1, colStart < 1 ? 0 : colStart);
+    LogicalPosition end =
+        new LogicalPosition(lineEnd < 1 ? 0 : lineEnd - 1, colEnd < 1 ? 0 : colEnd);
+    int startOffset = editor.logicalPositionToOffset(start);
+    int endOffset = editor.logicalPositionToOffset(end);
+    if (0 < startOffset && 0 < endOffset && startOffset < endOffset) {
+      TextRangeInterval range = new TextRangeInterval(startOffset - 1, endOffset - 1);
+      String message = info.message.replace('\n', ' ').replaceAll("\\s+", " ").trim();
+      LOG.debug("annotate " + startOffset + ":" + endOffset + " '" + message + "'");
```
Comment (giraud) [inline idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:290]: protect with LOG.isDebugEnabled

File: idea-plugin/src/com/reason/CompilerORProcessException.java (hunk 1 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/CompilerORProcessException.java:5]: good catch

File: idea-plugin/src/com/reason/bs/BsLineProcessor.java (hunk 2 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/bs/BsLineProcessor.java:163]: there's a slight difference. the new version of bs-platform uses a colon instead of a space between file names and line numbers

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 4 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:100]: cool to do this in a separate PR? I'd like to limit the scope of changes here

File: idea-plugin/src/com/reason/bs/BscProcess.java (hunk 5 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/bs/BscProcess.java:33]: done

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 10 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:248]: good call

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 14 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:107]: instead of deleting this file at the end of the process, i was instead deleting the entire temporary directory before compiling everything.

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 18 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:192]: done

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 13 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:78]: ah, couldn't find it because it was `private`

File: idea-plugin/src/com/reason/bs/BscProcessListener.java (hunk 9 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/bs/BscProcessListener.java:40]: this was copy-pasted. onTextAvailable is called frequently but we only want to trigger our processor when we see a newline.

`StringBuilder` pre-allocates memory for storing a string whereas string concatenation reallocates memory on each concatenation. Think resizing an ArrayList vs resizing an Array[]

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 4 above)
Comment (giraud) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:100]: yes. but I'm just talking about that particular line, that could be removed.

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 14 above)
Comment (giraud) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:107]: Not sure it works. is it ok if dir is not empty ? also createTemp might not be predictive (adding random numbers to always succeed) ? if something went wrong, you compile a dir with old files, that may produce unexpected result.... but maybe my comment is stupid

File: idea-plugin/src/com/reason/bs/BsLineProcessor.java (hunk 2 above)
Comment (giraud) [reply idea-plugin/src/com/reason/bs/BsLineProcessor.java:163]: oh right, didnt see it

File: idea-plugin/src/com/reason/bs/BscProcessListener.java (hunk 9 above)
Comment (giraud) [reply idea-plugin/src/com/reason/bs/BscProcessListener.java:40]: I didn't read code correctly, you're right

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 8 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:166]: This one took me a minute to think through.

There are 3 states for exit codes:

1. Error code is null --> means something went wrong, an exceptional situation
2. Error code is 0 --> all good, re-analyze the PSI, update (clear) error annotations
3. Error code is non-null, non-zero --> compilation error, update error annotations

Comment (giraud) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:166]: ok but in case error code is different from 0, do we really want to handle 2 cases ? I think writing a log is the only option we have. so even if null/non-zero has different meaning, I don't think it matters.

Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:166]: ok, I'll combine null and non-zero

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 14 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:107]: createTemp adds a number to the prefix only if a directory already exists with the same name. By deleting the directory before we create it, we guarantee that createTemp won't add a number prefix.

Also, the last `true` parameter in `FileUtil.createTempDirectory(directoryName, null, true);` is `deleteOnExit` which will delete the temporary directory when IntelliJ exists so long as it doesn't crash

File: idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java (hunk 4 above)
Comment (JohnPucciarelli) [reply idea-plugin/src/com/reason/ide/annotations/ErrorAnnotator.java:100]: oh wow, yeah didn't realize we weren't using the executable's path. removed.
